// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using getbiz_custom_app.Getbiz_DbContext;

namespace getbiz_custom_app.Migrations
{
    [DbContext(typeof(CustomApp_DbContext))]
    partial class CustomApp_DbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("getbiz_custom_app.Models.custom_app_about_demo", b =>
                {
                    b.Property<int>("custom_app_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("custom_app_attachments_file")
                        .HasColumnType("longtext");

                    b.Property<string>("custom_app_demo_video_file")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("custom_app_demo_video_timestamp_description_file")
                        .HasColumnType("datetime(6)");

                    b.HasKey("custom_app_id");

                    b.ToTable("custom_app_about_demo");
                });

            modelBuilder.Entity("getbiz_custom_app.Models.custom_app_additional_data", b =>
                {
                    b.Property<int>("user_app_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("can_this_app_be_displayed_in_customerbizapp_launch_screen")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("can_this_user_app_be_blocked_by_app_administrator")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("does_this_app_have_configuration_data_specific_to_this_app")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("user_app_id");

                    b.ToTable("custom_app_additional_data");
                });

            modelBuilder.Entity("getbiz_custom_app.Models.custom_app_cloud_file_storage_permissions", b =>
                {
                    b.Property<int>("custom_app_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("copy_file")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("delete_file")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("delete_folder")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("custom_app_id");

                    b.ToTable("custom_app_cloud_file_storage_permissions");
                });

            modelBuilder.Entity("getbiz_custom_app.Models.custom_app_comment", b =>
                {
                    b.Property<int>("comment_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("comment_reply")
                        .HasColumnType("longtext");

                    b.Property<string>("comment_text")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("comment_timestamp")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("comment_type")
                        .HasColumnType("int");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.HasKey("comment_id");

                    b.ToTable("custom_app_comment");
                });

            modelBuilder.Entity("getbiz_custom_app.Models.custom_app_communication", b =>
                {
                    b.Property<int>("communication_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("communication_text")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("communication_time_stamp")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.HasKey("communication_id");

                    b.ToTable("custom_app_communication");
                });

            modelBuilder.Entity("getbiz_custom_app.Models.custom_app_master", b =>
                {
                    b.Property<int>("custom_app_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("custom_app_icon_image")
                        .HasColumnType("longtext");

                    b.Property<string>("custom_app_icon_name")
                        .HasColumnType("longtext");

                    b.Property<string>("custom_app_web_link")
                        .HasColumnType("longtext");

                    b.HasKey("custom_app_id");

                    b.ToTable("custom_app_master");
                });

            modelBuilder.Entity("getbiz_custom_app.Models.custom_app_names", b =>
                {
                    b.Property<int>("custom_app_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("custom_app_icon_name")
                        .HasColumnType("longtext");

                    b.Property<string>("custom_app_name")
                        .HasColumnType("longtext");

                    b.Property<string>("custom_app_web_link")
                        .HasColumnType("longtext");

                    b.HasKey("custom_app_id");

                    b.ToTable("custom_app_names");
                });

            modelBuilder.Entity("getbiz_custom_app.Models.custom_apps_customers_list", b =>
                {
                    b.Property<int>("custom_app_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("customer_id")
                        .HasColumnType("int");

                    b.Property<string>("user_apps_to_be_hidden")
                        .HasColumnType("longtext");

                    b.HasKey("custom_app_id");

                    b.ToTable("custom_apps_customers_list");
                });

            modelBuilder.Entity("getbiz_custom_app.Models.custom_apps_update_time_stamp", b =>
                {
                    b.Property<int>("custom_app_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("custom_app_update_timestamp")
                        .HasColumnType("datetime(6)");

                    b.HasKey("custom_app_id");

                    b.ToTable("custom_apps_update_time_stamp");
                });
#pragma warning restore 612, 618
        }
    }
}
